version: "3.8"
services:
  database:
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - vdata_database:/var/lib/mysql
  maildev:
    image: maildev/maildev
    restart: always
  messenger:
    build:
      context: ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    command: ['php', 'bin/console', 'messenger:consume', 'priority_high', 'priority_normal', 'priority_low', '-vv']
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - "./app/:/var/www"
  nginx:
    image: nginx:alpine
    links:
      - maildev
      - php
      - phpmyadmin
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    restart: always
    volumes:
      - "./app/:/var/www"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/site.dev.conf:/etc/nginx/conf.d/default.conf"
  node:
    build:
      context: ./docker/node
    command:
      - yarn run build
    user: '${USER_ID}:${GROUP_ID}'
    volumes:
      - ./app/:/usr/src/app
    working_dir: /usr/src/app
  minio:
    command: server /data --console-address ":9001"
    environment:
      MINIO_BROWSER_REDIRECT_URL: ${DOCKER_MINIO_CONSOLE}
      MINIO_ROOT_USER: ${DOCKER_MINIO_KEY}
      MINIO_ROOT_PASSWORD: ${DOCKER_MINIO_SECRET}
    image: minio/minio
    restart: unless-stopped
    volumes:
      - vdata_minio:/data
  php:
    build:
      context: ./docker/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    links:
      - database
      - maildev
    restart: always
    volumes:
      - "./app/:/var/www"
  phpmyadmin:
    depends_on:
      - database
    environment:
      PMA_ABSOLUTE_URI: ${DOCKER_DATABASE_URI}
      PMA_HOST: database
    image: phpmyadmin
    restart: always
  redis:
    image: redis:6-alpine
    restart: always
  redis-gui:
    environment:
      - REDIS_HOSTS=local:redis:6379
    image: rediscommander/redis-commander
    restart: always
  swagger:
    environment:
      SWAGGER_JSON: /foo/swagger.json
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - "./app/swagger.json:/foo/swagger.json"
volumes:
  vdata_database:
  vdata_minio: