_default:
    resource: ../../src/UI/_default
    type: annotation

frontoffice:
    name_prefix: frontoffice.
    prefix:
        en: "/en/"
        fr: "/fr/"
    resource: ../../src/UI/FrontOffice
    type: annotation

adminoffice:
    name_prefix: adminoffice.
    prefix:
        en: "/en/admin/"
        fr: "/fr/admin/"
    resource: ../../src/UI/AdminOffice
    type: annotation

api_v2:
    name_prefix: api.v2.
    prefix: "/api/v2/"
    resource: ../../src/UI/API/V2
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
