security:
    access_control:
        - { path: ^/(fr|en)/admin/login.html, roles: PUBLIC_ACCESS }
        - { path: ^/(fr|en)/admin, roles: ROLE_USER }
        - { path: ^/(fr|en)/manage/login.html, roles: PUBLIC_ACCESS }
        - { path: ^/(fr|en)/manage/login/microsoft.html, roles: PUBLIC_ACCESS }
        - { path: ^/(fr|en)/manage/login/microsoft/callback.html, roles: PUBLIC_ACCESS }
        - { path: ^/(fr|en)/manage, roles: ROLE_USER }

    enable_authenticator_manager: true

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_v2_login:
            pattern: ^/api/v2/login
            security: false
        api_v2:
            custom_authenticators:
                - App\Application\Security\APIV2Authenticator
            pattern: ^/api/v2/
            provider: system_apiv2_provider
        adminoffice:
            custom_authenticators:
                - App\Application\Security\MultiAuthenticator
            form_login:
                always_use_default_target_path: true
                check_path: adminoffice.security.login
                default_target_path: adminoffice.dashboard.index
                enable_csrf: true
                login_path: adminoffice.security.login
            logout:
                path: backoffice.security.logout
            pattern: ^/(fr|en)/manage/
            provider: system_user_username_provider
        backoffice:
            custom_authenticators:
                - App\Application\Security\MultiAuthenticator
            form_login:
                always_use_default_target_path: true
                check_path: backoffice.security.login
                default_target_path: backoffice.dashboard.index
                enable_csrf: true
                login_path: backoffice.security.login
            logout:
                path: backoffice.security.logout
            pattern: ^/(fr|en)/admin/
            provider: system_user_username_provider

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        system_apiv2_provider:
            chain:
                providers: [system_user_id_provider]
        system_user_username_provider:
            entity:
                class: App\Domain\_mysql\System\Entity\User
                property: username
        system_user_id_provider:
            entity:
                class: App\Domain\_mysql\System\Entity\User
                property: id